# Generated by Django 6.1 on 2026-08-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку для оплаты",
                max_length=450,
                null=True,
                verbose_name="Ссылка для оплаты",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите id сессии",
                max_length=255,
                null=True,
                verbose_name="id сессии оплаты",
            ),
        ),
    ]
