# Generated by Django 6.1 on 2026-08-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку для оплаты",
                max_length=950,
                null=True,
                verbose_name="Ссылка для оплаты",
            ),
        ),
    ]
