# Generated by Django 6.1 on 2026-08-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="price",
        ),
    ]
