# Generated by Django 6.1 on 2026-08-13 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                help_text="Выберите курс",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson",
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        help_text="Введите дату платежа", verbose_name="Дата платежа"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        help_text="Введите сумму платежа", verbose_name="Сумма платежа"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("cash", "Наличные"), ("transfer", " на счет")],
                        help_text="Выберите способ платежа",
                        verbose_name="Способ платежа",
                    ),
                ),
                (
                    "paid_course",
                    models.ForeignKey(
                        help_text="Выберите курс",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paid_course",
                        to="materials.course",
                        verbose_name="Оплаченный курс",
                    ),
                ),
                (
                    "paid_lesson",
                    models.ForeignKey(
                        help_text="Выберите урок",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paid_lesson",
                        to="materials.lesson",
                        verbose_name="Оплаченный урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Выберите платеж",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Платеж",
                    ),
                ),
            ],
        ),
    ]
