# Generated by Django 6.1 on 2026-08-13 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_lesson_course_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="paid_course",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите курс",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paid_course",
                to="materials.course",
                verbose_name="Оплаченный курс",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите урок",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paid_lesson",
                to="materials.lesson",
                verbose_name="Оплаченный урок",
            ),
        ),
    ]
