# Generated by Django 6.1 on 2026-08-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_payment_paid_course_alter_payment_paid_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="paid_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="Введите сумму платежа",
                max_digits=10,
                null=True,
                verbose_name="Сумма платежа",
            ),
        ),
    ]
