# Generated by Django 6.1 on 2026-08-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_alter_payment_paid_amount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
