# Generated by Django 6.1 on 2026-08-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_subscription_created_at_alter_subscription_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.FloatField(blank=True, null=True, verbose_name="Цена курса"),
        ),
    ]
