# Generated by Django 6.1 on 2026-08-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0009_course_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Укажите цену курса",
                null=True,
                verbose_name="Цена курса",
            ),
        ),
    ]
