# Generated by Django 6.1 on 2026-08-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0010_alter_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
