# Generated by Django 6.1 on 2026-08-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0011_course_stripe_price_id_course_stripe_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True,
                help_text="Укажите цену курса",
                null=True,
                verbose_name="Цена курса",
            ),
        ),
    ]
