# Generated by Django 6.1 on 2026-08-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0012_alter_course_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="stripe_price_id",
        ),
        migrations.RemoveField(
            model_name="course",
            name="stripe_product_id",
        ),
    ]
