# Generated by Django 5.2.17 on 2026-08-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0013_remove_course_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Укажите цену курса",
                max_digits=10,
                null=True,
                verbose_name="Цена курса",
            ),
        ),
    ]
